### ISSUE TITLE
MOOSDB Race Condition in XPCGetProtocol.cpp

### ISSUE THREAD

**Issue by mmoseley** [themoos/core-moos#2]
There is a race condition between threads in the MOOSDB caused by getprotobyname and getprotobynumber in XPCGetProtocol.cpp.  The result is that the tcp server in the MOOSCommServer can be set as UDP instead of TCP resulting in the listen call continuously throwing an 'operation not supported' exception and putting the MOOSDB into a busy loop.   

The solution is to change the getprotobyname and getprotobynumber calls in XPCGetProtocol.cpp to the thread-safe reentrant versions, getprotobyname_r and get protobynumber_r.  The Linux Man page for getprotobyname_r provides a good example of the changes necessary.

**Comment by arh-oxbotica** [comment]
This issue seems to have been addressed by 0ece27ec6954cb250434. Suggest you close the issue now @pnewman.
