### ISSUE TITLE
Commit 1e61cbb has broken essential-moos

### ISSUE THREAD

**Issue by arh-oxbotica** [themoos/core-moos#37]
Since commit 1e61cbb in `core-moos`, `essential-moos` fails to build.

This is the commit in question:
```
------------------------------------------------------------
commit 1e61cbb23f45b2d3b93568243f0518a13e3b1e9e
Author: Paul Newman <pnewman@Pauls-MBP.home.gateway>
Date:   Sat Jun 10 20:39:37 2017 +0100

    putative efficiency in CMOOSCommPkt

 5 files changed, 79 insertions(+), 102 deletions(-)
------------------------------------------------------------
```

and the error message in `essential-moos` is this:
```
<redacted>/essential-moos/Essentials/pMOOSBridge/MOOSUDPLink.cpp:173:19: error: no member named 'Fill' in 'CMOOSCommPkt'
            PktRx.Fill(pBuffer+q,nRqd);
            ~~~~~ ^
1 error generated.
```

**Comment by msis** [comment]
As far as I remember, `pMOOSBridge` was abandoned  and replaced by `pShare`. 

We should just comment the `add_subdirectory(pMOOSBridge)` in `CMakeLists.txt` or completely delete it.
Pretty sure no one is using it anymore.

**Comment by pmnewman** [comment]
closed  - I updated pMOOSBridge to use the updated API.
