### ISSUE TITLE
PeriodicEvent.cpp: Build error in MSVC 2012

### ISSUE THREAD

**Issue by jlblancoc** [themoos/core-moos#8]
Hi, 

This is a minor issue: MSVC complains about Stop() not returning a value: 

```
        bool Stop()
        {
            Thread_.Stop();
        }
```

should be (I guess):

```
        bool Stop()
        {
            return Thread_.Stop();
        }
```

Best,
JL

**Comment by arh-oxbotica** [comment]
I think this would actually be UB, right? Anyway, I believe it was fixed in e1b435f62f2a. I suggest you close this issue now, @pmnewman.
